spring.application.name: authenticated-api-demo

server.port: 8081

jwt:
  public-key-base64: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAswfvl2KlhYRIFul4VjgHWwGKmMRit0bRZvQEZhTi0xbfF51+kXIPdMh/Vc9s8p0IAJKe3bNWPSfqULcKZ61MK6YDLQYqaAGK1pXG2WNiUztgEMfD/BMjbvOQXIpjsvkA96txEw7HCgn7M8bmFqCJ00IlszQm1u7Z0+V+wbWq366pmtDtbRqb8lgrFAXHDjBfvZoqy7ftmyp8OXSFGk/vekxUzNYkvUsYFhqppb3PUz5nS9aDbPavHIB1hNVqeaDGXd9Jze+aXUsKp7j70ntg2u+eGMfm8eIzdrICxXPj/4GnNnpXRIDdF3JTFIVCjB384Y1eAZtar61B21QhSQLJ0wIDAQAB
